
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE FUNCTION public.insert_mondays_between(start_date date, end_date date, semester_value character varying) RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    current_date_ DATE;
BEGIN
    -- Find the first Monday on or after the start date
    current_date_ := start_date + CAST(((7 - EXTRACT(DOW FROM start_date) + 1) % 7) AS INTEGER) * INTERVAL '1 day';

    -- Loop through the dates and insert Mondays
    WHILE current_date_ BETWEEN start_date AND end_date LOOP
        INSERT INTO public.week (monday, semester) VALUES (current_date_, semester_value);
        current_date_ := current_date_ + INTERVAL '7 days'; -- Move to next Monday
    END LOOP;
END;
$$;


ALTER FUNCTION public.insert_mondays_between(start_date date, end_date date, semester_value character varying) OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 16623)
-- Name: asset; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.asset (
    id integer NOT NULL,
    file_name character varying(255) NOT NULL,
    last_modified timestamp(6) without time zone NOT NULL,
    editor integer NOT NULL
);


ALTER TABLE public.asset OWNER TO "etwig.test";

--
-- TOC entry 225 (class 1259 OID 16626)
-- Name: asset_id_seq; Type: SEQUENCE; Schema: public; Owner: etwig.test
--

ALTER TABLE public.asset ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.asset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 16479)
-- Name: event; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.event (
    id integer NOT NULL,
    is_recurring boolean DEFAULT false NOT NULL,
    organizer integer NOT NULL,
    portfolio integer NOT NULL
);


ALTER TABLE public.event OWNER TO "etwig.test";

--
-- TOC entry 211 (class 1259 OID 16483)
-- Name: etwig_events_EventID_seq; Type: SEQUENCE; Schema: public; Owner: etwig.test
--

ALTER TABLE public.event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."etwig_events_EventID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16397)
-- Name: etwig_events_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.etwig_events_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.etwig_events_seq OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16484)
-- Name: event_recurring; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.event_recurring (
    id integer NOT NULL,
    name character varying(31) NOT NULL,
    description character varying(65535),
    location character varying(63),
    frequency character varying(63) NOT NULL,
    duration integer NOT NULL,
    available_from timestamp(6) without time zone,
    available_to timestamp(6) without time zone
);


ALTER TABLE public.event_recurring OWNER TO "etwig.test";

--
-- TOC entry 213 (class 1259 OID 16489)
-- Name: event_single_time; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.event_single_time (
    id integer NOT NULL,
    name character varying(31) NOT NULL,
    description character varying(65535),
    location character varying(63),
    start_datetime timestamp(6) without time zone NOT NULL,
    duration integer NOT NULL,
    override_recurring_event integer,
    unit "char"
);


ALTER TABLE public.event_single_time OWNER TO "etwig.test";

--
-- TOC entry 223 (class 1259 OID 16606)
-- Name: graphic; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.graphic (
    id integer NOT NULL,
    disk_location character varying NOT NULL,
    upload_datetime timestamp without time zone NOT NULL,
    operator_id integer NOT NULL,
    event_id integer NOT NULL
);


ALTER TABLE public.graphic OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16605)
-- Name: graphics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.graphic ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.graphics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16494)
-- Name: users; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.users (
    id integer NOT NULL,
    first_name character varying(31) NOT NULL,
    middle_name character varying(31),
    last_name character varying(31) NOT NULL,
    email character varying(63) NOT NULL,
    password character varying(63) NOT NULL,
    last_login timestamp(6) without time zone DEFAULT now() NOT NULL,
    permission integer NOT NULL
);


ALTER TABLE public.users OWNER TO "etwig.test";

--
-- TOC entry 215 (class 1259 OID 16498)
-- Name: leader_id_seq; Type: SEQUENCE; Schema: public; Owner: etwig.test
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leader_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16499)
-- Name: option; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.option (
    id integer NOT NULL,
    name character varying(31) NOT NULL,
    color character varying(7) NOT NULL,
    belongs_to integer NOT NULL
);


ALTER TABLE public.option OWNER TO "etwig.test";

--
-- TOC entry 217 (class 1259 OID 16502)
-- Name: options_id_seq; Type: SEQUENCE; Schema: public; Owner: etwig.test
--

ALTER TABLE public.option ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16503)
-- Name: permission; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.permission (
    id integer NOT NULL,
    name character varying(31) NOT NULL
);


ALTER TABLE public.permission OWNER TO "etwig.test";

--
-- TOC entry 219 (class 1259 OID 16506)
-- Name: portfolio; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.portfolio (
    id integer NOT NULL,
    name character varying(31) NOT NULL,
    color character varying(15) DEFAULT 0 NOT NULL,
    abbreviation character varying(15),
    icon character varying(31),
    is_seperated_calendar boolean NOT NULL,
    parent integer
);


ALTER TABLE public.portfolio OWNER TO "etwig.test";

--
-- TOC entry 220 (class 1259 OID 16510)
-- Name: portfolio_id_seq; Type: SEQUENCE; Schema: public; Owner: etwig.test
--

ALTER TABLE public.portfolio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16641)
-- Name: twig_template; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.twig_template (
    portfolio_id integer NOT NULL,
    id integer NOT NULL,
    background jsonb NOT NULL
);


ALTER TABLE public.twig_template OWNER TO "etwig.test";

--
-- TOC entry 227 (class 1259 OID 16662)
-- Name: portfolio_twig_template_id_seq; Type: SEQUENCE; Schema: public; Owner: etwig.test
--

ALTER TABLE public.twig_template ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.portfolio_twig_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16511)
-- Name: user_role; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.user_role (
    user_id integer NOT NULL,
    portfolio_id integer NOT NULL,
    "position" character varying(63) NOT NULL
);


ALTER TABLE public.user_role OWNER TO "etwig.test";

--
-- TOC entry 228 (class 1259 OID 16668)
-- Name: week; Type: TABLE; Schema: public; Owner: etwig.test
--

CREATE TABLE public.week (
    id integer NOT NULL,
    name character varying(31) NOT NULL,
    semester character varying(31) NOT NULL,
    monday date NOT NULL
);


ALTER TABLE public.week OWNER TO "etwig.test";

--
-- TOC entry 229 (class 1259 OID 16694)
-- Name: week_id_seq; Type: SEQUENCE; Schema: public; Owner: etwig.test
--

ALTER TABLE public.week ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.week_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3252 (class 2606 OID 16631)
-- Name: asset asset_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.asset
    ADD CONSTRAINT asset_pkey PRIMARY KEY (id);


--
-- TOC entry 3229 (class 2606 OID 16515)
-- Name: event etwig_events_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT etwig_events_pkey PRIMARY KEY (id);


--
-- TOC entry 3244 (class 2606 OID 16517)
-- Name: portfolio etwig_portfolio_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.portfolio
    ADD CONSTRAINT etwig_portfolio_pkey PRIMARY KEY (id);


--
-- TOC entry 3234 (class 2606 OID 16519)
-- Name: event_single_time event_single_time_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.event_single_time
    ADD CONSTRAINT event_single_time_pkey PRIMARY KEY (id);


--
-- TOC entry 3231 (class 2606 OID 16521)
-- Name: event_recurring events_recurring_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.event_recurring
    ADD CONSTRAINT events_recurring_pkey PRIMARY KEY (id);


--
-- TOC entry 3250 (class 2606 OID 16612)
-- Name: graphic graphics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.graphic
    ADD CONSTRAINT graphics_pkey PRIMARY KEY (id);


--
-- TOC entry 3240 (class 2606 OID 16523)
-- Name: option options_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.option
    ADD CONSTRAINT options_pkey PRIMARY KEY (id);


--
-- TOC entry 3242 (class 2606 OID 16525)
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (id);


--
-- TOC entry 3254 (class 2606 OID 16661)
-- Name: twig_template portfolio_twig_template_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.twig_template
    ADD CONSTRAINT portfolio_twig_template_pkey PRIMARY KEY (id);


--
-- TOC entry 3256 (class 2606 OID 16705)
-- Name: week uni_monday; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.week
    ADD CONSTRAINT uni_monday UNIQUE (monday);


--
-- TOC entry 3248 (class 2606 OID 16527)
-- Name: user_role user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (user_id, portfolio_id);


--
-- TOC entry 3238 (class 2606 OID 16529)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3258 (class 2606 OID 16672)
-- Name: week week_pkey; Type: CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.week
    ADD CONSTRAINT week_pkey PRIMARY KEY (id);


--
-- TOC entry 3235 (class 1259 OID 16530)
-- Name: fki_event_id_fkey; Type: INDEX; Schema: public; Owner: etwig.test
--

CREATE INDEX fki_event_id_fkey ON public.event_single_time USING btree (id);


--
-- TOC entry 3232 (class 1259 OID 16531)
-- Name: fki_i; Type: INDEX; Schema: public; Owner: etwig.test
--

CREATE INDEX fki_i ON public.event_recurring USING btree (id);


--
-- TOC entry 3245 (class 1259 OID 16532)
-- Name: fki_portfolio_id_fkey; Type: INDEX; Schema: public; Owner: etwig.test
--

CREATE INDEX fki_portfolio_id_fkey ON public.user_role USING btree (portfolio_id);


--
-- TOC entry 3246 (class 1259 OID 16533)
-- Name: fki_user_id_fkey; Type: INDEX; Schema: public; Owner: etwig.test
--

CREATE INDEX fki_user_id_fkey ON public.user_role USING btree (user_id);


--
-- TOC entry 3236 (class 1259 OID 16534)
-- Name: user_group_fkey; Type: INDEX; Schema: public; Owner: etwig.test
--

CREATE INDEX user_group_fkey ON public.users USING btree (permission);


--
-- TOC entry 3260 (class 2606 OID 16535)
-- Name: event_single_time event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.event_single_time
    ADD CONSTRAINT event_id_fkey FOREIGN KEY (id) REFERENCES public.event(id) NOT VALID;


--
-- TOC entry 3259 (class 2606 OID 16540)
-- Name: event_recurring event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.event_recurring
    ADD CONSTRAINT event_id_fkey FOREIGN KEY (id) REFERENCES public.event(id) NOT VALID;


--
-- TOC entry 3266 (class 2606 OID 16632)
-- Name: asset fk_editor; Type: FK CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.asset
    ADD CONSTRAINT fk_editor FOREIGN KEY (editor) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 3265 (class 2606 OID 16618)
-- Name: graphic fk_event; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.graphic
    ADD CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES public.event(id) NOT VALID;


--
-- TOC entry 3264 (class 2606 OID 16613)
-- Name: graphic fk_operator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.graphic
    ADD CONSTRAINT fk_operator FOREIGN KEY (operator_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 3261 (class 2606 OID 16545)
-- Name: users permission_fkey; Type: FK CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT permission_fkey FOREIGN KEY (permission) REFERENCES public.permission(id) NOT VALID;


--
-- TOC entry 3262 (class 2606 OID 16550)
-- Name: user_role portfolio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT portfolio_id_fkey FOREIGN KEY (portfolio_id) REFERENCES public.portfolio(id) NOT VALID;


--
-- TOC entry 3263 (class 2606 OID 16555)
-- Name: user_role user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: etwig.test
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


-- Completed on 2024-01-03 10:40:25 UTC

--
-- PostgreSQL database dump complete
--
