--
-- PostgreSQL database dump
--

-- Dumped from database version 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)

-- Started on 2023-11-30 21:09:38 AEDT!

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 16394)
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    event_id integer NOT NULL,
    name character varying(255) NOT NULL,
    location character varying(255) NOT NULL,
    description character varying(65535) NOT NULL,
    user_id integer NOT NULL,
    end_time character varying(255) NOT NULL,
    start_time character varying(255) NOT NULL
);


ALTER TABLE public.events OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16401)
-- Name: etwig_events_EventID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."etwig_events_EventID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 16405)
-- Name: etwig_events_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.etwig_events_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.etwig_events_seq OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16406)
-- Name: portfolio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portfolio (
    id integer NOT NULL,
    name character varying(31) NOT NULL,
    color character varying(15) DEFAULT 0 NOT NULL
);


ALTER TABLE public.portfolio OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16412)
-- Name: portfolio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portfolio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3355 (class 0 OID 16394)
-- Dependencies: 209
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.events (event_id, name, location, description, user_id, end_time, start_time) FROM stdin;
1	11	11	11	1	1999-01-08 04:05:06	1999-01-08 04:05:06
\.


--
-- TOC entry 3358 (class 0 OID 16406)
-- Dependencies: 212
-- Data for Name: portfolio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portfolio (id, name, color) FROM stdin;
2	Social	0000FF
1	Sports	00FF00
\.


--
-- TOC entry 3365 (class 0 OID 0)
-- Dependencies: 210
-- Name: etwig_events_EventID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."etwig_events_EventID_seq"', 5, true);


--
-- TOC entry 3366 (class 0 OID 0)
-- Dependencies: 211
-- Name: etwig_events_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.etwig_events_seq', 1, false);


--
-- TOC entry 3367 (class 0 OID 0)
-- Dependencies: 213
-- Name: portfolio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portfolio_id_seq', 2, true);


--
-- TOC entry 3213 (class 2606 OID 16400)
-- Name: events etwig_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT etwig_events_pkey PRIMARY KEY (event_id);


--
-- TOC entry 3215 (class 2606 OID 16411)
-- Name: portfolio etwig_portfolio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portfolio
    ADD CONSTRAINT etwig_portfolio_pkey PRIMARY KEY (id);


-- Completed on 2023-11-30 21:09:38 AEDT

--
-- PostgreSQL database dump complete
--

